@Library('library')_

pipeline
{
    agent any
    stages
      {
        stage('ContinuousDownload_personalbanking')
          {
            steps
              {
                script
                  {
                     library.newGit("https://github.com/intelliqittrainings/maven.git")
                  }
              }
          }
         stage('ContinuousBuild_personalbanking')
          {
            steps
              {
                script
                  {
                     library.newMaven()
                  }
              }
          }
     }
}
