@Library('library')_

pipeline
{
    agent any
    stages
      {
        stage('ContinuousDownload_loans')
          {
            steps
              {
                script
                  {
                     library.newGit("https://github.com/intelliqittrainings/maven.git")
                  }
              }
          }
         stage('ContinuousBuild_loans')
          {
            steps
              {
                script
                  {
                     library.newMaven()
                  }
              }
          }
     }
}
